// Generates sitemap.xml from the .html files sitting next to this script.
//
// The site is static, so there is no build step to hang this off: hosting just
// serves the repo. sitemap.xml is therefore committed, and this script exists
// to keep it honest whenever a page is added, renamed or edited.
//
//   npm run sitemap
//
// Order, priority and lastmod are all derived, so a new artist page only needs
// the usual <title> and "plate NN" eyebrow to slot in correctly.

'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');

const ROOT = __dirname;
const ORIGIN = 'https://unitedhallucinations.com';
const OUT_FILE = path.join(ROOT, 'sitemap.xml');

// Files that are not pages. index_old.html is a dead prototype that links
// nowhere useful, and keeping it out stops it competing with the real index.
const NOT_PAGES = new Set(['index_old.html']);

// The index is the one page every other page links back to, so it leads.
const HOME = 'index.html';

function readPages() {
  return fs
    .readdirSync(ROOT, { withFileTypes: true })
    .filter((e) => e.isFile() && e.name.endsWith('.html') && !NOT_PAGES.has(e.name))
    .map((e) => e.name);
}

function read(file) {
  return fs.readFileSync(path.join(ROOT, file), 'utf8');
}

// The artist pages carry "plate NN" in their eyebrow and are laid out in plate
// order, so the sitemap follows the same order readers see on the index.
function plateOf(html) {
  const m = html.match(/plate\s+(\d+)/i);
  return m ? Number(m[1]) : Number.MAX_SAFE_INTEGER;
}

function titleOf(html, file) {
  const m = html.match(/<title>([^<]*)<\/title>/i);
  if (!m) {
    console.warn(`  ! ${file} has no <title>, crawlers will have nothing to index`);
    return null;
  }
  return m[1].trim();
}

function descriptionOf(html, file) {
  if (!/name=["']description["']/i.test(html)) {
    console.warn(`  ! ${file} has no meta description, search results will improvise one`);
  }
}

// lastmod is when a crawler last saw real content change, which is what git
// knows better than the filesystem does. Falls back to mtime outside a checkout
// (e.g. a tarball deploy) and on files git has not seen yet.
function lastmodOf(file) {
  try {
    const out = execFileSync('git', ['log', '-1', '--format=%cs', '--', file], {
      cwd: ROOT,
      stdio: ['ignore', 'pipe', 'ignore'],
    })
      .toString()
      .trim();
    if (out) return out;
  } catch {
    // not a git repo, or git refused
  }
  return fs.statSync(path.join(ROOT, file)).mtime.toISOString().slice(0, 10);
}

// index.html is served at the root. Every other URL is the real filename,
// because nothing guarantees the host rewrites /kor.html to /kor, and a
// sitemap that points at 404s is worse than no sitemap at all. If clean URLs
// are ever set up, this is the one place that changes.
function locFor(file) {
  return file === HOME ? `${ORIGIN}/` : `${ORIGIN}/${file}`;
}

function buildPages() {
  const files = readPages();

  if (!files.includes(HOME)) {
    throw new Error(`${HOME} is missing; every sitemap needs a root URL.`);
  }

  return files
    .map((file) => ({ file, html: read(file) }))
    .sort((a, b) => {
      if (a.file === HOME) return -1;
      if (b.file === HOME) return 1;
      return plateOf(a.html) - plateOf(b.html) || a.file.localeCompare(b.file);
    })
    .map(({ file, html }) => {
      titleOf(html, file);
      descriptionOf(html, file);
      return {
        loc: locFor(file),
        lastmod: lastmodOf(file),
        changefreq: file === HOME ? 'weekly' : 'monthly',
        priority: file === HOME ? '1.0' : '0.7',
      };
    });
}

function render(pages) {
  const lines = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!-- Generated by sitemap.js (npm run sitemap). Edit that script, not this file. -->',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
  ];

  for (const p of pages) {
    lines.push(
      '  <url>',
      `    <loc>${p.loc}</loc>`,
      `    <lastmod>${p.lastmod}</lastmod>`,
      `    <changefreq>${p.changefreq}</changefreq>`,
      `    <priority>${p.priority}</priority>`,
      '  </url>',
    );
  }

  lines.push('</urlset>', '');
  return lines.join('\n');
}

const pages = buildPages();
fs.writeFileSync(OUT_FILE, render(pages));

console.log(`wrote ${path.relative(ROOT, OUT_FILE)} — ${pages.length} url(s)`);
for (const p of pages) {
  console.log(`  ${p.loc}  (${p.lastmod})`);
}
